---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: static-site
  namespace: default
spec:
  valuesFrom:
  - kind: ConfigMap
    name: static-site-configmap
  interval: 1m
  chart:
    spec:
      chart: static-site
      #version: v1.6.0
      sourceRef:
        kind: GitRepository
        name: static-site