---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: static-site
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/my-flux/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: static-site
  targetNamespace: default

