---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: static-site
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/kedark0kil/docker-curriculum/
  ref:
    branch: master
  secretRef:
    name: static-site
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: static-site
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: static-site
  targetNamespace: default
