---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: static-site
  namespace: default
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/kedark0kil/docker-curriculum/