apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-files
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    #assigns labels to the pods for future selection
    matchLabels:
      app: static-files
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: static-files
    spec:
      containers:
      - name: task-fluxcd
        image: kedark0kil/task-fluxcd
        ports:
          - name: http
            containerPort: 80
