apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: static-site
  namespace: default
spec:
  interval: 1m0s
  url: https://hub.docker.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: static-site
  namespace: default
spec:
  valuesFrom:
  - kind: ConfigMap
    name: static-site-configmap
  interval: 2m
  chart:
    spec:
      chart: static-site
      sourceRef:
        kind: HelmRepository
        name: static-site