apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- static-site/flux/my-flux/static-kustomization.yaml
- static-site/flux/my-flux/static-site-source.yaml