---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: static-site
  namespace: default
spec:
  interval: 30s
  path: ./static-site/flux/my-flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: static-site
  targetNamespace: default

