on: 
  pull_request:
      branches: 
        - staging
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker logout
        
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io

        DOCKER_BUILDKIT=1 docker build static-site/. --file static-site/Dockerfile --tag kedark0kil/task-fluxcd:$(docker images | awk '($1 == "kedark0kil/task-fluxcd") {print $2 += .01; exit}')

        docker push kedark0kil/task-fluxcd:$(docker images | awk '($1 == "kedark0kil/task-fluxcd") {print $2 += .01; exit}')
