on: 
  pull_request:
      branches: 
        - staging
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker logout
        
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io

        DOCKER_BUILDKIT=1 docker build static-site/. --file static-site/Dockerfile --tag kedark0kil/task-fluxcd:${{ secrets.MAJOR }}.${{ secrets.MINOR }}

        docker push kedark0kil/task-fluxcd:${{ secrets.MAJOR }}.${{ secrets.MINOR }}
    -
      name: Update Minor version
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'MINOR'
        value: $((${{ secrets.MINOR }}+1))
        repository: kedark0kil/task-fluxcd
        token: ${{ secrets.GITHUB_TOKEN }}
