name: ci

on:
  push:
    branches:
      - 'master'
      - 'staging'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build 
        run: |
          DOCKER_BUILDKIT=1 docker build . --file static-site/Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
      -
        name: push
        uses: docker/build-push-action@v4
        with:
          push: true
